### ISSUE TITLE
Release / publication

### ISSUE THREAD

**Issue by romanzdk** [moneymeets/youtrack-sdk#32]
Would it be possible to create a new release for the library and/or publish the package to PyPI and/or create a new tag with every new "version", please? That way it would be easier to use the SDK in projects

**Comment by catcombo** [comment]
Sorry for the late response. Thank you for the idea! We have decided to use PyPI, but we need some time to discuss details internally in our team. I'll let you know when we publish a first release on PyPI.

**Comment by catcombo** [comment]
Hi @romanzdk!

`youtrack-sdk` is now available on the PyPI: https://pypi.org/project/youtrack-sdk/

Thank you!
