### ISSUE TITLE
Add work items endpoints and models

### ISSUE THREAD

**Issue by andreasciamanna** [moneymeets/youtrack-sdk#41]
Hi,

I've been using this library for a couple of weeks, as it seems the most maintained and well-made.

However, I just realised it lacks support for [work items](https://www.jetbrains.com/help/youtrack/devportal/resource-api-issues-issueID-timeTracking-workItems.html#get_all-IssueWorkItem-method-sample): reading and creating.

Can it be added?

I would try myself, but I barely started grasping how to write a Python app, let alone a module :D

**Comment by zyv** [comment]
@andreasciamanna please check my comment in #42 - /cc @catcombo

**Comment by catcombo** [comment]
@andreasciamanna please have a look and test PR I created.

**Comment by andreasciamanna** [comment]
@catcombo 

I wrote some code in my project that does the same things, but in a much uglier way (as I hinted yesterday, Python is not quite my nature).

I'll see if I can install your branch in my project and test it.

I'll keep an eye on the MR anyway.

Thanks!

**Comment by catcombo** [comment]
@andreasciamanna You're welcome! Once the PR is approved by all reviewers and merged, new package version will automatically be released on PyPI in the same day.

**Comment by catcombo** [comment]
@andreasciamanna PR merged, new version released on PyPI. You can now update `youtrack-sdk` locally and use it instead of git branch version.

**Comment by andreasciamanna** [comment]
I was using the unmerged version, which was already working fine.

I updated the package now, which is also working, of course.

Great job, @catcombo!

Thanks.
