### ISSUE TITLE
Authorization header is not added to requests

### ISSUE THREAD

**Issue by jbtibor** [moneymeets/youtrack-sdk#46]
I'm passing in a perm token as in the example code:
`client = Client(base_url="https://dummy.youtrack.cloud/api", token="perm:1234")`

However, the requests fail with YouTrackUnauthorized error.

If I modify client.py `_send_request` method to add the Authorization header the requests are authorized.
```
        response = self._session.request(
            method=method,
            url=url,
            data=data and obj_to_json(data),
            files=files,
            headers=data and {"Authorization": "Bearer perm:1234"},
            timeout=self._timeout,
        )
```

Is this a bug or I'm doing something wrong?

**Comment by catcombo** [comment]
Hi @jbtibor !

1. What method did you call when received `YouTrackUnauthorized` error?
2. Are you sure that the token you are using has enough permissions to call this method or access data?

**Comment by jbtibor** [comment]
I called create_issue and the same token worked when hardcoded in _session.request and curl.

However, it just started working magically, sorry about the false alarm. No idea why it failed before.

**Comment by catcombo** [comment]
Sure, no problem.
